AWSTemplateFormatVersion: "2010-09-09"
  Description: "Simple, single EC2 Instance template"
  Resources:
    EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-7ea24a17

        AvailabilityZone: "us-east-1"